[package]
name = "shared"
description = "shared"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
serde = {workspace = true} 